TOOLS = [
    {"name": "pc_reindex", "description": "⚠️ DESTRUCTIVE — 인덱스 전체 재구성. 일상 워크플로에서는 watcher 기반 증분 인덱싱이 자동 동작하므로 호출 불필요. 파서 수정·DB 오염·스키마 마이그레이션 같은 명시적 사유가 있을 때만 사용. force=true는 file_cache 전체 무효화 + 모든 파일 재파싱·재임베딩(GPU 비용) 발생.", "inputSchema": {"type": "object", "properties": {"force": {"type": "boolean", "description": "⚠️ destructive. 호출 시 사유(파서 수정/DB 오염 등)를 명시할 것"}}}},
    {"name": "pc_index_status", "description": "인덱스 상태", "inputSchema": {"type": "object"}},
    {"name": "pc_index_roots_list", "description": "현재 인덱싱 루트 설정 조회", "inputSchema": {"type": "object"}},
    {"name": "pc_index_roots_add", "description": "settings.local.yaml에 인덱싱 루트 추가. 기본 dry_run=true로 스캔 수만 계산.", "inputSchema": {"type": "object", "properties": {"path": {"type": "string", "description": "워크스페이스 기준 상대 경로 또는 워크스페이스 내부 절대 경로"}, "dry_run": {"type": "boolean", "default": True}}, "required": ["path"]}},
    {"name": "pc_index_roots_remove", "description": "settings.local.yaml의 인덱싱 루트 제거. 기본 dry_run=true로 스캔 수만 계산.", "inputSchema": {"type": "object", "properties": {"path": {"type": "string", "description": "제거할 인덱싱 루트"}, "dry_run": {"type": "boolean", "default": True}}, "required": ["path"]}},
    {"name": "pc_capsule", "description": "1순위 검색. token_budget는 chars/4 추정 기반(정확한 토크나이저 아님). auto_chain=true 시 짧은 capsule 감지 후 impact_graph+memory 자동 체이닝 + observation 기록을 수행한다. 응답에 chars_used/tokens_estimated 포함.", "inputSchema": {"type": "object", "properties": {"query": {"type": "string"}, "token_budget": {"type": "integer", "description": "토큰 예산 (approximate via chars/4)", "default": 4000}, "auto_chain": {"type": "boolean", "description": "짧은 capsule 시 자동 체이닝 활성화", "default": False}}, "required": ["query"]}},
    {"name": "pc_skeleton", "description": "파일 스켈레톤 출력.", "inputSchema": {"type": "object", "properties": {"file_path": {"type": "string", "description": "파일 경로"}, "detail": {"type": "string", "description": "상세 수준", "enum": ["minimal", "standard", "detailed"], "default": "standard"}}, "required": ["file_path"]}},
    {"name": "pc_impact_graph", "description": "영향 범위 추적. 응답에 truncated/limit/returned_count/total_seen 포함.", "inputSchema": {"type": "object", "properties": {"fqn": {"type": "string", "description": "함수/클래스의 FQN"}, "direction": {"type": "string", "description": "추적 방향", "enum": ["callers", "callees", "both"], "default": "both"}, "max_depth": {"type": "integer", "description": "최대 깊이", "default": 2}, "max_nodes": {"type": "integer", "description": "최대 반환 노드 수", "default": 50}}, "required": ["fqn"]}},
    {"name": "pc_logic_flow", "description": "두 기능 간 실행 경로 탐색. 응답에 truncated/limit/returned_count/total_seen 포함.", "inputSchema": {"type": "object", "properties": {"from_fqn": {"type": "string", "description": "시작 지점 FQN"}, "to_fqn": {"type": "string", "description": "종료 지점 FQN"}, "max_depth": {"type": "integer", "description": "경로 최대 깊이", "default": 6}, "max_nodes": {"type": "integer", "description": "탐색 최대 노드 수", "default": 200}}, "required": ["from_fqn", "to_fqn"]}},
    {"name": "pc_git_log", "description": "특정 파일의 상세 Git 수정 이력 조회.", "inputSchema": {"type": "object", "properties": {"file_path": {"type": "string", "description": "파일 경로"}, "limit": {"type": "integer", "description": "최대 로그 수", "default": 5}}, "required": ["file_path"]}},
    {"name": "pc_run_pipeline", "description": "캡슐+임팩트+메모리 통합 검색 (고급 종합 탐색 진입점). 코드+그래프+메모리 종합 맥락이 필요한 경우 사용. 응답에 truncated/limit/returned_count/total_seen 포함.", "inputSchema": {"type": "object", "properties": {"query": {"type": "string", "description": "통합 검색 쿼리"}, "limit": {"type": "integer", "description": "unified_context 항목 수 제한", "default": 5}}, "required": ["query"]}},
    {"name": "pc_auto_context", "description": "세션 시작 시 최신 결정사항과 인기 지식을 요약하여 제공 (맥락 복원).", "inputSchema": {"type": "object", "properties": {"token_budget": {"type": "integer", "description": "토큰 예산", "default": 2000}}}},
    {"name": "pc_read_with_hash", "description": "해시 포함 읽기", "inputSchema": {"type": "object", "properties": {"file_path": {"type": "string"}}, "required": ["file_path"]}},
    {"name": "pc_strict_replace", "description": "정밀 편집", "inputSchema": {"type": "object", "properties": {"file_path": {"type": "string"}, "old_content": {"type": "string"}, "new_content": {"type": "string"}}, "required": ["file_path", "old_content", "new_content"]}},
    {"name": "pc_create_contract", "description": "계약 생성", "inputSchema": {"type": "object", "properties": {"lane_id": {"type": "string"}, "task_name": {"type": "string"}, "instructions": {"type": "string"}}, "required": ["lane_id", "task_name", "instructions"]}},
    {"name": "pc_todo_manager", "description": "Todo 관리", "inputSchema": {"type": "object", "properties": {"action": {"type": "string", "description": "add | check | clear"}, "task": {"type": "string", "description": "add 시 등록할 태스크 내용"}, "task_id": {"type": "string", "description": "check 시 완료 표시할 태스크 ID"}}, "required": ["action"]}},
    {"name": "pc_session_sync", "description": "작업 종료 시 Git 상태와 변경 파일을 스캔하여 세션 메모리를 자동 동기화합니다.", "inputSchema": {"type": "object", "properties": {"task_desc": {"type": "string", "description": "작업 요약"}}, "required": ["task_desc"]}},
    {"name": "pc_memory_write", "description": "지식 저장 및 마크다운 승격(decisions/patterns.md)", "inputSchema": {"type": "object", "properties": {"key": {"type": "string"}, "category": {"type": "string"}, "content": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "relationships": {"type": "object"}}, "required": ["key", "category", "content"]}},
    {"name": "pc_memory_consolidate", "description": "파편화된 과거 지식을 하나의 새로운 규칙으로 병합. dry_run=true 기본 — 후보만 반환(would_delete/would_write/executed=false). 실행하려면 dry_run=false 명시. 자동 트리거 금지.", "inputSchema": {"type": "object", "properties": {"new_key": {"type": "string"}, "category": {"type": "string"}, "content": {"type": "string"}, "old_keys": {"type": "array", "items": {"type": "string"}}, "tags": {"type": "array", "items": {"type": "string"}}, "relationships": {"type": "object"}, "dry_run": {"type": "boolean", "description": "기본 true. false 명시 시에만 실제 삭제·병합 수행", "default": True}}, "required": ["new_key", "category", "content", "old_keys"]}},
    {"name": "pc_memory_read", "description": "지식 조회", "inputSchema": {"type": "object", "properties": {"key": {"type": "string"}}, "required": ["key"]}},
    {"name": "pc_save_observation", "description": "인사이트 저장", "inputSchema": {"type": "object", "properties": {"content": {"type": "string"}}, "required": ["content"]}},
    {"name": "pc_memory_search_knowledge", "description": "영구 지식, 규칙 및 스킬 하이브리드 검색", "inputSchema": {"type": "object", "properties": {"query": {"type": "string"}, "category": {"type": "string"}}, "required": ["query"]}}
]

def list_tools():
    return TOOLS
